"""M3-03 API 合同包：业务 DTO、审核请求与统一错误结构（规格 12 节）。"""

from app.modules.application.api.contracts.errors import (
    ERROR_HTTP_STATUS,
    ApiErrorCode,
    BusinessError,
    CaseProcessingErrorCode,
    ProcessingErrorStage,
    install_error_boundary,
)
from app.modules.application.api.contracts.reviews import (
    ApprovedReviewRequest,
    InsufficientEvidenceReviewRequest,
    ModifiedApprovedReviewRequest,
    RejectedWithJudgmentReviewRequest,
    ReviewOutcome,
    ReviewRequest,
)
from app.modules.application.api.contracts.views import (
    ACTION_CATALOG_VERSION,
    ACTION_TYPE_OPTIONS,
    CAUSE_CATEGORY_OPTIONS,
    INTERVENTION_LEVEL_OPTIONS,
    ActionView,
    BatchListView,
    BatchWorkspaceView,
    CaseDetailView,
    CaseProcessingErrorView,
    CaseQueueItemView,
    CaseQueueView,
    CauseView,
    CitedEvidenceView,
    EvidenceModality,
    ReviewOptionsView,
    ReviewResultView,
    build_review_options,
)

__all__ = [
    "ACTION_CATALOG_VERSION",
    "ACTION_TYPE_OPTIONS",
    "ApiErrorCode",
    "ActionView",
    "ApprovedReviewRequest",
    "BatchListView",
    "BatchWorkspaceView",
    "BusinessError",
    "CAUSE_CATEGORY_OPTIONS",
    "CaseDetailView",
    "CaseProcessingErrorCode",
    "CaseProcessingErrorView",
    "CaseQueueItemView",
    "CaseQueueView",
    "CauseView",
    "CitedEvidenceView",
    "ERROR_HTTP_STATUS",
    "EvidenceModality",
    "InsufficientEvidenceReviewRequest",
    "INTERVENTION_LEVEL_OPTIONS",
    "ModifiedApprovedReviewRequest",
    "ProcessingErrorStage",
    "RejectedWithJudgmentReviewRequest",
    "ReviewOptionsView",
    "ReviewOutcome",
    "ReviewRequest",
    "ReviewResultView",
    "build_review_options",
    "install_error_boundary",
]
