# ruff: noqa: E501
"""initial nine tables

Revision ID: dc4c1050e0af
Revises:
Create Date: 2026-09-06 15:45:22.623656
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'dc4c1050e0af'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('STARTING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', 'INTERRUPTED', name='batch_runs_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('total_case_count', sa.Integer(), nullable=False),
    sa.Column('analysis_succeeded_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(
        'uq_batch_runs_one_active',
        'batch_runs',
        [sa.literal_column('1')],
        unique=True,
        sqlite_where=sa.text("status IN ('STARTING', 'RUNNING')"),
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=128), nullable=False),
    sa.Column('data_version_id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('package_sha256', sa.String(length=64), nullable=False),
    sa.Column('package_relative_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING_ANALYSIS', 'ANALYZING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', name='batches_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('analysis_succeeded_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('current_batch_run_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_batch_run_id'], ['batch_runs.id'], ),
    sa.ForeignKeyConstraint(['data_version_id'], ['data_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_table('case_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('batch_run_id', sa.Integer(), nullable=True),
    sa.Column('previous_case_run_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.Enum('BATCH', 'MANUAL_RERUN', name='case_runs_trigger_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('STARTING', 'PERCEPTION_RUNNING', 'ATTRIBUTION_RUNNING', 'STRATEGY_RUNNING', 'SUCCEEDED', 'FAILED', 'INTERRUPTED', name='case_runs_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_stage', sa.String(length=64), nullable=True),
    sa.Column('error_detail_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_run_id'], ['batch_runs.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['previous_case_run_id'], ['case_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('uq_case_runs_one_active_per_case', 'case_runs', ['case_id'], unique=True, sqlite_where=sa.text("status IN ('STARTING', 'PERCEPTION_RUNNING', 'ATTRIBUTION_RUNNING', 'STRATEGY_RUNNING')"))
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('case_input_json', sa.JSON(), nullable=False),
    sa.Column('customer_display_id', sa.String(length=255), nullable=False),
    sa.Column('is_high_value', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_ANALYSIS', 'ANALYZING', 'PENDING_REVIEW', 'COMPLETED', 'PROCESSING_ERROR', name='cases_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('system_intervention_level', sa.Enum('MUST_INTERVENE', 'SHOULD_INTERVENE', 'NO_IMMEDIATE_INTERVENTION', name='cases_system_intervention_level', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('final_intervention_level', sa.Enum('MUST_INTERVENE', 'SHOULD_INTERVENE', 'NO_IMMEDIATE_INTERVENTION', name='cases_final_intervention_level', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('current_case_run_id', sa.Integer(), nullable=True),
    sa.Column('current_review_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['current_case_run_id'], ['case_runs.id'], ),
    sa.ForeignKeyConstraint(['current_review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'case_id', name='uq_cases_batch_id_case_id')
    )
    op.create_table('data_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_version', sa.String(length=128), nullable=False),
    sa.Column('source_snapshot_ref', sa.String(length=255), nullable=False),
    sa.Column('source_manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_version')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=128), nullable=False),
    sa.Column('submission_id', sa.String(length=128), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('case_run_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('APPROVED', 'MODIFIED_AND_APPROVED', 'REJECTED_WITH_JUDGMENT', 'INSUFFICIENT_EVIDENCE', name='reviews_outcome', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('final_intervention_level', sa.Enum('MUST_INTERVENE', 'SHOULD_INTERVENE', 'NO_IMMEDIATE_INTERVENTION', name='reviews_final_intervention_level', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('final_cause_json', sa.JSON(), nullable=True),
    sa.Column('final_actions_json', sa.JSON(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['case_run_id'], ['case_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_reviews_case_id'),
    sa.UniqueConstraint('review_id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=128), nullable=False),
    sa.Column('modality', sa.String(length=32), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('identity', sa.String(length=128), nullable=False),
    sa.Column('relation_identity', sa.String(length=128), nullable=False),
    sa.Column('source_ref_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'evidence_id', name='uq_evidence_case_id_evidence_id')
    )
    op.create_table('model_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('case_run_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=64), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('request_manifest_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_token_count', sa.Integer(), nullable=True),
    sa.Column('completion_token_count', sa.Integer(), nullable=True),
    sa.Column('total_token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_run_id'], ['case_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('stage_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_run_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=64), nullable=False),
    sa.Column('contract_version', sa.String(length=64), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('result_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_run_id'], ['case_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_run_id', 'stage_name', name='uq_stage_results_case_run_id_stage_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_results')
    op.drop_table('model_calls')
    op.drop_table('evidence')
    op.drop_table('reviews')
    op.drop_table('data_versions')
    op.drop_table('cases')
    op.drop_index('uq_case_runs_one_active_per_case', table_name='case_runs', sqlite_where=sa.text("status IN ('STARTING', 'PERCEPTION_RUNNING', 'ATTRIBUTION_RUNNING', 'STRATEGY_RUNNING')"))
    op.drop_table('case_runs')
    op.drop_table('batches')
    op.drop_index(
        'uq_batch_runs_one_active',
        table_name='batch_runs',
        sqlite_where=sa.text("status IN ('STARTING', 'RUNNING')"),
    )
    op.drop_table('batch_runs')
    # ### end Alembic commands ###

